config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index', as: 'store_index'

  resources :products

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static/Pages'
  
  root "store#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
        current_item.quantity += 1
        else
        current_item = line_items.build(product_id: product.id)
        end
        current_item
    end
    
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  
  belongs_to :product
  belongs_to :cart
  def total_price
    product.price * quantity
  end
  
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  
  belongs_to :cart 

  def total_price 
  product.price * quantity 
  end 
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    
  enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
  }
    validates :name, :address, :email, presence: true
    validates :pay_type, inclusion: pay_types.keys
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
    item.cart_id = nil
    line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  has_many :line_items
     before_destroy :ensure_not_referenced_by_any_line_item
     
     private
     # ensure that there are no line items referencing this product
       def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
         errors.add(:base, 'Line Items present')
        throw :abort
        end
       end
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
class Error < StandardError
end
private
def ensure_an_admin_remains
if User.count.zero?
raise Error.new "Can't delete last user"
end
end
end

app/models/user1.rb
class User1 < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  #skip_before_action :authorize
  skip_before_action :authorize, only: [:create, :update, :destroy, :show]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url,
        notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
    
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart'
    end
    
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user1s_helper.rb
module User1sHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit :Submit, class:"w3-button w3-red" %>
  </div>
<% end %>

app/views/carts/edit.html.erb
 <div class="w3-container w3-center"><p><h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart, class: "w3-button w3-red" %> |
<%= link_to 'Back', carts_path, class: "w3-button w3-red" %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

 <div class="w3-container w3-center"><p><h1>Cart</h1>

<table class="w3-table-all">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart, class: "w3-button w3-red" %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart), class: "w3-button w3-red" %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }, class: "w3-button w3-red" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path, class: "w3-button w3-red" %>

app/views/carts/new.html.erb
 <div class="w3-container w3-center"><p><h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path, class: "w3-button w3-red" %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="w3-table-all"> 
	
	<div class="panel-body">
 <table class="table table-responsive">
    
    <% @cart.line_items.each do |item| %>
    <tr><td><%= item.quantity %> &times;</td>
    <td><%= item.product.title %></td>
    <td><%= number_to_currency(item.total_price) %></td>
    <td><%= image_tag(item.product.image_url)%></td>
	 </tr>
	  <% end %>
    <tr>
    <td></td><td>Total Order Value </td><td><%= number_to_currency(@cart.total_price) %></td><td></td>
    </tr>
    <tr><td></td><td><%= link_to 'Keep Shopping', store_index_url , class:"w3-button w3-red" %></td>
    <td><%= button_to 'Empty cart', @cart, class: "w3-button w3-red", method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= button_to "Checkout", new_order_path, method: :get, data: { confirm: 'Are you sure you want to checkout?' }, class: "w3-button w3-red"%></td>
 </table>
</div>