config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index', as: 'store_index'

  resources :products

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static/Pages'
  
  root "store#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
        current_item.quantity += 1
        else
        current_item = line_items.build(product_id: product.id)
        end
        current_item
    end
    
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  
  belongs_to :product
  belongs_to :cart
  def total_price
    product.price * quantity
  end
  
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  
  belongs_to :cart 

  def total_price 
  product.price * quantity 
  end 
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    
  enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
  }
    validates :name, :address, :email, presence: true
    validates :pay_type, inclusion: pay_types.keys
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
    item.cart_id = nil
    line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  has_many :line_items
     before_destroy :ensure_not_referenced_by_any_line_item
     
     private
     # ensure that there are no line items referencing this product
       def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
         errors.add(:base, 'Line Items present')
        throw :abort
        end
       end
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
class Error < StandardError
end
private
def ensure_an_admin_remains
if User.count.zero?
raise Error.new "Can't delete last user"
end
end
end

app/models/user1.rb
class User1 < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authorize, only: [:show, :new, :create]
  include CurrentCart
 before_action :set_cart, only: [:create]
 before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart}
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
     #params.require(:line_item).permit(:product_id, :cart_id)
     params.require(:line_item).permit(:product_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user1s_helper.rb
module User1sHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w3-panel">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :line_item_product_id, class: "w3-input" %>
  </div>

  <div class="w3-panel">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, id: :line_item_cart_id, class: "w3-input" %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class:"w3-button w3-red"%>
  </div>
<% end %>

app/views/line_items/edit.html.erb
 <div class="w3-container w3-center"><p><h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item, class: "w3-button w3-red" %> |
<%= link_to 'Back', line_items_path, class: "w3-button w3-red" %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

 <div class="w3-container w3-center"><p><h1>Line Items</h1></p></div>

<table class="w3-table w3-bordered w3-white"
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item, class: "w3-button w3-red" %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item), class: "w3-button w3-red" %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }, class: "w3-button w3-red" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path, class: "w3-button w3-red" %>

app/views/line_items/new.html.erb
 <div class="w3-container w3-center"><p><h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path, class: "w3-button w3-red" %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>
<div class="w3-panel w3-white w3-border w3-round-small">
<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item), class: "w3-button w3-red" %> |
<%= link_to 'Back', line_items_path, class: "w3-button w3-red" %>