config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index', as: 'store_index'

  resources :products

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static/Pages'
  
  root "store#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
        current_item.quantity += 1
        else
        current_item = line_items.build(product_id: product.id)
        end
        current_item
    end
    
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  
  belongs_to :product
  belongs_to :cart
  def total_price
    product.price * quantity
  end
  
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  
  belongs_to :cart 

  def total_price 
  product.price * quantity 
  end 
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    
  enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
  }
    validates :name, :address, :email, presence: true
    validates :pay_type, inclusion: pay_types.keys
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
    item.cart_id = nil
    line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  has_many :line_items
     before_destroy :ensure_not_referenced_by_any_line_item
     
     private
     # ensure that there are no line items referencing this product
       def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
         errors.add(:base, 'Line Items present')
        throw :abort
        end
       end
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
class Error < StandardError
end
private
def ensure_an_admin_remains
if User.count.zero?
raise Error.new "Can't delete last user"
end
end
end

app/models/user1.rb
class User1 < ApplicationRecord
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user1s_helper.rb
module User1sHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="w3-container w3-center"><h1>Welcome</h1>
It's <%= Time.now.in_time_zone ("Central Time (US & Canada)") %><br>
We have <%= pluralize(@total_orders, "order") %>.</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="w3-container w3-grey">
    <div>
      <a href="/static_pages/home" class="w3-button w3-red">Home</a>
      <a href="/store/index" class="w3-button w3-red">Store</a>
      <a href="/static_pages/help" class="w3-button w3-red">Help</a>
      <a href="/static_pages/about" class="w3-button w3-red">About</a>
      <%= link_to 'Login', login_path, method: :post, class:"w3-button w3-red" %>
      <% if session[:user_id] %>
       
       <%= link_to 'Orders', orders_path, class: "w3-button w3-red" %>
       <%= link_to 'Products', products_path, class:"w3-button w3-red" %>
       <%= link_to 'Users', users_path, class:"w3-button w3-red" %>
       <a href="/carts" class="w3-button w3-red">Shopping Cart</a>
      <a href="/line_items" class="w3-button w3-red">Line Items</a>
       
       <%= link_to 'Logout', logout_path, method: :delete, class:"w3-button w3-red" %>
       <% end %>
    </ul>
    <%= yield %>
  </body>
</html>


 